### ISSUE TITLE
Error on unicode character

### ISSUE THREAD

**Issue by sapraaman** [cjhutto/bsd#19]
We were trying to run bias detector on text available [here](https://www.theguardian.com/uk-news/2015/aug/10/10-truths-about-europes-refugee-crisis). Bias detector fails because it cannot handle unicode character. The first sentence which fails is:

`But to do that, you need facts and data – two things that the British migration debate has lacked this summer.`

If I remove the hyphen with an ascii minus sign, it works:

`But to do that, you need facts and data - two things that the British migration debate has lacked this summer.`

```
/Users/aman/Work/colab/NewsFrames/bias-detector/bsd/bsdetector/bias.py:186: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if w in feat_list:
/Users/aman/Work/colab/NewsFrames/bias-detector/bsd/bsdetector/bias.py:189: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if b in feat_list:
/Users/aman/Work/colab/NewsFrames/bias-detector/bsd/bsdetector/bias.py:192: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if t in feat_list:
Traceback (most recent call last):
  File "newsframe.py", line 48, in <module>
    csv_normalized_bias_components(sentences)
  File "newsframe.py", line 33, in csv_normalized_bias_components
    print to_csv(compute_normalized_bias_components(s))
  File "newsframe.py", line 20, in compute_normalized_bias_components
    features = bias.extract_bias_features(sentence)
  File "/Users/aman/Work/colab/NewsFrames/bias-detector/bsd/bsdetector/bias.py", line 354, in extract_bias_features
    count = count_phrase_freq(coherence, txt_lwr)
  File "/Users/aman/Work/colab/NewsFrames/bias-detector/bsd/bsdetector/bias.py", line 200, in count_phrase_freq
    if phrase in txt_lwr:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 40: ordinal not in range(128)
```

Also tried handling utf-8 before passing it to bias detector as suggested in readme. However, the error remains, except the error now mentions unicode character differently.

`UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 40: ordinal not in range(128)`

**Comment by cjhutto** [comment]
I *think* this might fix the issue:
   Try explicitly converting to acsii from utf-8 (so that the external modules can work on them), and tell Python to ignore the unknown characters...
   Insert the following line to the "extract_bias_features" function (insert at line 333), and change the following line to reference the 'atext' variable when preserving hyphens:
```
332    features = OrderedDict()
333    asciitext = text.decode('ascii', 'ignore') # ignore conversion errors between utf-8 and ascii
334    text_nohyph = asciitext.replace("-", " ")  # preserve hyphenated words as separate tokens
```

**Comment by cjhutto** [comment]
In my limited quick test (scraped all the text from the web page you referenced) it seemed to work...

**Comment by connieimdialog** [comment]
thanks @cjhutto, @sapraaman let's try again with the new version of BSD.
if it doesn't work, i did figure out the other thing that was making it break, so if we're still having issues:
*   ’ instead of '  \xe2\x80\x99 instead of \x27
*   search for example for .`..bear them out. When you’re...`

**Comment by jpfairbanks** [comment]
I noticed this diff:

```diff
@@ -330,7 +331,8 @@ liwc_work = ref_lexicons.list('ref_liwc_work')
 
 def extract_bias_features(text):
     features = OrderedDict()
-    text_nohyph = text.replace("-", " ")  # preserve hyphenated words as seperate tokens
+	acsiitext = text.decode('ascii', 'ignore') # ignore conversion errors between utf-8 and ascii
+    text_nohyph = acsiitext.replace("-", " ")  # preserve hyphenated words as separate tokens
     txt_lwr = str(text_nohyph).lower()
     words = ''.join(ch for ch in txt_lwr if ch not in '!"#$%&()*+,-./:;<=>?@[\]^_`{|}~').split()
     unigrams = sorted(list(set(words)))
```

ignore means that utf-8 characters that aren't in ascii will be silently dropped.

https://docs.python.org/3/howto/unicode.html#the-string-type
> In addition, one can create a string using the decode() method of bytes. This method takes an encoding argument, such as UTF-8, and optionally an errors argument.
>
> The errors argument specifies the response when the input string can’t be converted according to the encoding’s rules. Legal values for this argument are 'strict' (raise a UnicodeDecodeError exception), 'replace' (use U+FFFD, REPLACEMENT CHARACTER), 'ignore' (just leave the character out of the Unicode result), or 'backslashreplace' (inserts a \xNN escape sequence). The following examples show the differences:

I don't think this is what you want. This is probably fine for punctuation that doesn't terminate a sentence. But, I think you would want to correctly handle utf characters by choosing the most appropriate ascii version for everything else. The lexicons used by the algorithm are ASCII so words containing non-ascii characters would not be correctly characterized anyway.

**Comment by cjhutto** [comment]
Silently dropping Unicode or UTF-8 characters that are unknown to ASCII is not the ideal solution, but note that "replace" and "backslashreplace" to not resolve the issue.  We might need to look into something like [Unidecode ](https://pypi.python.org/pypi/Unidecode)to do a translation... which would mean adding another external to our requirements.txt

**Comment by jpfairbanks** [comment]
Yes that makes sense. But in order to handle text with accent or foreign language words, the model would need to be trained with those in the training data.

There are three levels of unicode support:

1. Code doesn't crash: `ignore` gets us here
2.  Code maps unicode to ascii and is best effort.
3. Code handles unicode and gives "correct" answers for texts using foreign characters.

I think we need more diverse training data to get to 3.
